[package]
name = "rnd-cmd"
description = "A CLI tool to get random number"
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"

[[bin]]
name = "rnd"
path = "./src/main.rs"

[dependencies]
rand = "0.9.2"
clap = { version = "4", features = ["derive"] }
num = "0.4"
